language: python

python:
  - 3.6

matrix:
  include:
    - python: 3.6
      env: RANDOM_SEED=37

install:
  - pip install coverage
  - pip install python-coveralls

script:
  - nosetests --with-coverage . tests

after_success:
  - coveralls
  