language: python

python:
  - 3.6

matrix:
  include:
    - python: 3.6
      env: RANDOM_SEED=37
      env: PYTHONPATH=$PYTHONPATH:code

install:
  - pip install coverage
  - pip install python-coveralls

script:
  - nosetests --with-coverage --cover-package=csv_readers,groups,ids,multi,utils ./code/tests

after_success:
  - coveralls
  
