language: python

python:
  - 3.6

matrix:
  include:
    - python: 3.6
      env: RANDOM_SEED=37

script:
  - nosetests --with-coverage test_csv_readers.py

install:
  - pip install codecov

script:
  - coverage run test_csv_readers.py

after_success:
  - codecov --token=cde1d454-fe69-41b7-89b6-ccff2010683a
